version: "3.7"
services:
  pgAdmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 3000:3000
  
  nginx:
    build:
      context: ./nginx
    ports:
      - 4000:80
    restart: always

  db:
    image: postgres:latest
    hostname: db
    volumes: 
      - /var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=server
  
  redis:
    image: redis:latest
    restart: always
    env_file:
      - ./.env
      
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./client:/app
    expose:
      - 3000
  
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./server:/app
    env_file: 
      - ./.env
    expose: 
      - 3000
    depends_on: 
      - db
  
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    ports: 
      - 8082:3000
    volumes: 
      - /app/node_modules
      - ./worker:/app
    env_file:
      - ./.env

  

  
